### ISSUE TITLE
Leaving 

### ISSUE THREAD

**Issue by MeganSpauldingCreative** [GWGweb-projectgroup/practice-project#101]
Hey guys, I think I am going to have to bow out! My daughter has been teething and running my own group project is about all I've been able to handle right now! Just wanted to let you know! Thanks for being willing to include me.

**Comment by elementWebDev** [comment]
It was nice having you on the team Megan, thanks for your help and fresh
ideas :)

**Comment by ddpetty** [comment]
Thank you for your help!!!!

**Comment by Cynth42** [comment]
Thank you helping out @MeganSpauldingCreative!
