### ISSUE TITLE
Using PHP

### ISSUE THREAD

**Issue by elementWebDev** [GWGweb-projectgroup/practice-project#102]
I'm working on centralizing the header, nav, content, and footer.
I've been having issues with my editors picking up the extension with my server though, so working on getting it together.

**Comment by ddpetty** [comment]
So the plan is to use PHP for the back end?

**Comment by elementWebDev** [comment]
Just to keep from repeating code across pages

**Comment by chrisvneal** [comment]
PHP baby! lol that's cool hope this gives me a chance to study up on some things. Hopefully we'll be able to

* template out a lot of the html page headers and footers

* flesh out that product.html template with data for whatever product we select

**Comment by elementWebDev** [comment]
Thats the point, so you don't have to edit the same code on every page

**Comment by Cynth42** [comment]
Hey You all!
Do you want to share this project on [code corps](https://www.codecorps.org/code-corps/code-corp)?  That way we could get more contributors?

**Comment by ddpetty** [comment]
I'm up for that idea! I wish I was able to contribute more frequently, but
some extra bills popped up and I have to work more instead of coding more.
What does everyone else think?

**Comment by Cynth42** [comment]
Don't know yet @ddpetty - waiting to hear from everyone else :)

**Comment by elementWebDev** [comment]
Yes..php will be used for backend.Go ahead and continue to work on your
features,

- I will need help getting products info and images, i started a list in
products.js (look to see whats needed)

- We had permission to use the assets from https://megagoods.com

**Comment by elementWebDev** [comment]
Oops replied from email to wrong thread it seems

**Comment by Cynth42** [comment]
Where can I get some good resources on php? Don't know php, but I'm good with ruby

**Comment by Cynth42** [comment]
I'll also look at product.js to see what can be done there.  What are you working on in product.js @elementWebDev ?

**Comment by elementWebDev** [comment]
So far its just a product list to pull from

**Comment by elementWebDev** [comment]
This is gonna be fun! All kinds of ideas for differant modules after brushing up on the php. This is an opprtunity for all teams in html, css, and javascript

**Comment by chrisvneal** [comment]
Nice @elementWebDev, I hope we can all bring whatever technologies we are currently learning to the table and help each other learn & master them. I'm currently learning 

* node / npm / **Gulp** _(task runner)_

* modern workflow, etc.

Has anyone gotten into the _"modern workflow"_ world of CLI task runners & build tools _(Gulp, [webpack](https://webpack.js.org/), etc)_? 

It's pretty interesting once you get the hang of it. When I get comfortable with it and if anyone else wants to try and get into it, I'll include it in our workflow along with some basic instructions to get started.

![](https://www.arpatech.com/img/cms/php1-icon.png.pagespeed.ce.-Ww0U8G7Kl.png)

[Learn php from Codecademy](https://www.codecademy.com/en/tracks/php)

![](https://camo.githubusercontent.com/2d78b03f66a6ba65037abc89f403b1058c3c49e4/687474703a2f2f692e696d6775722e636f6d2f5270744a4d35512e706e67)

[Learn Gulp from CSS-tricks](https://css-tricks.com/gulp-for-beginners/)

**Comment by elementWebDev** [comment]
@chrisvneal I havent gotten into any of that, however Ive been working on php mysql so we can get this in a database to pull from.

   All of this is great... Continuing in this project we'll get to build a reusable ecommerce platform. After managing eCommerce sites(various platforms) for years I have many ideas that can be implemented, (i.e. subscription service, etc).

**Comment by ddpetty** [comment]
I have gotten into Gulp. It makes web dev so easy while you just focus on
code.

**Comment by chrisvneal** [comment]
@GWGweb-projectgroup 

That's great! 

I wouldn't mess with Gulp unless you're really comfortable with the command line. I'm trying to learn something new everyday. 

Between today and tomorrow I'll be looking into making **xmlhttp requests**, may be needing that sometime in the future 😉

**Comment by elementWebDev** [comment]
This issue is out of the scope of the project.. Have been working with node and react which has the ability to work with databases and create apps versus websites. I will come back to this later and edit. Lets keep up the project.

**Comment by elementWebDev** [comment]
Ok.. Here's the edit ya'll... Finally!

So we all have been out of the scholarship for awhile, however I've still been working on e-commerce.

- I have a product list we can work with
- working with the Vue.js frontend
- using Vue Storefront (setup and ready for implementation)

- Vue Storefront is backend agnostic ( meaning it can be used with any backend CMS.

I will create another branch on this repo for those interested... 

This is a chance to get your feet wet and have fun collaborating!

There's a lot to do... And a bit to learn too.

Cheers!
@taskmaster (Ivan Huddleston)

P.S. Please comment to let me know if you're interested
