### ISSUE TITLE
Moving Forward

### ISSUE THREAD

**Issue by chrisvneal** [GWGweb-projectgroup/practice-project#26]
What's up @GWGweb-projectgroup

Welcome @Cynth42!

We can all begin working on this project. The concept of the site is really simple and we can go over more as the week progresses, but we will be working on a **mock e-commerce site**. 

### Quick Notes

* I included [pictures](https://github.com/GWGweb-projectgroup/practice-project/tree/master/img) for the @GWGweb-projectgroup/layout team and @GWGweb-projectgroup/index-html team to work on, but feel free to gather any new pictures you find from other sources

* I included a [**Workflow.md** file](https://github.com/GWGweb-projectgroup/practice-project/blob/master/Workflow.md) for any newcomers and for anyone else who needs to understand a basic _GitHub collaboration workflow_ with this group specifically

* Check out @elementWebDev's [wireframes](https://github.com/GWGweb-projectgroup/practice-project/tree/dev/wireframes) to help kickstart the main page! _Thanks again for getting that crackin'._ I'm learning **Bootstrap** as I do the project

* Participate or leave the group

I'm so excited to start. **Let's do this!** 😃

**Comment by darenjm** [comment]
Good morning, this is exciting!

Daren Morreale
WordPress Website Designer
www.darenjm.com
USA: (347) 467-1093
Colombia: +57 (321) 926-1600 - whatsapp
skype: darenjm444

**Comment by Cynth42** [comment]
Hey Chris! This is great - We can do this! But Wireframe link is down; needs fixing.

**Comment by chrisvneal** [comment]
OK @Cynth42  I'll look into it thanks

**Comment by elementWebDev** [comment]
the link is wireframes/proto.png

**Comment by elementWebDev** [comment]
also img/home.png, img/products.png, img/product.png

**Comment by chrisvneal** [comment]
@Cynth42  which wireframe link are you referring to? The team name links work and I can view the .png file. Was it somewhere in the README?

**Comment by Cynth42** [comment]
I clicked on the link right here in issue: Check out @elementWebDev's wireframes to help kickstart the main page! but it took me to a 404 page.  I'll just look in .png file. Thanks!

**Comment by chrisvneal** [comment]
Hey @Cynth42 thanks for checking that, I just fixed it and added the link.

**Comment by elementWebDev** [comment]
Thanks Chris

Just an update, I'm working on a products page and waiting until i have something decent to commit.

**Comment by chrisvneal** [comment]
@elementWebDev thanks! Remember, ideas are welcome too. Don't feel that a feature has to be 100% done to commit!

**Comment by elementWebDev** [comment]
ok... how about this..
 
Create folder for each feature with its own files to be integrated in the root when finished
-or-
would it be better to have it all in one file to be dissected?

**Comment by elementWebDev** [comment]
i only ask because there were a whole bunch of commits while I was working on it lol

**Comment by chrisvneal** [comment]
@elementWebDev if you have a new feature that your working on that you aren't too sure you want to incorporate yet into the project (for example PHP/mySQL functionality, maybe another framework, etc.), create another branch for it on your local machine so you can also continue to work on the site with the regular stuff _(Bootstrap classes, CSS, simple JavaScript)_ in your local **[dev]** branch.

So your _local branches_ would look something like this: 

**_typical branches we all work from_**

* **[master]** - where you would pull the latest changes from the main repo

* **[dev]** - where you make changes to be pushed back to your GitHub acct's **[dev]** branch to make the pull request to be reviewed

**_separate branches - (languages everyone may not know yet)_**

* **[php_idea]** - to be pushed _(when your ready)_, reviewed and merged

* **[ruby-idea]** - to be pushed _(when your ready)_, reviewed and merged

**Comment by elementWebDev** [comment]
![product-on-hover](https://user-images.githubusercontent.com/12195875/37314996-5e7a2b1e-2614-11e8-9fa9-4292cd88f105.png)
screen shot of product image on hover

**Comment by elementWebDev** [comment]
I like that idea @chrisvneal

**Comment by chrisvneal** [comment]
@elementWebDev Looking over the code now, nice work! What I'll do is merge everything into the **[dev]** branch and pull it so I can see the site. Looks good to me, I don't see any issues so far. 👍

**Comment by elementWebDev** [comment]
Continuing the conversation from <a href="https://github.com/GWGweb-projectgroup/practice-project/pull/41">PR #41</a>...

Since we're only doing 2-3 pages, I'm assuming we should have all products on one page in different sections. On Sale items either on the home or on top of products page?

Anyone else with ideas... please feel free to jump in  👍

**Comment by anvarov** [comment]
hello everyone, just wanted to know, how app will run (i mean server, database etc)? 
and do we have special requirements about that, for example when implementing user authorization, will we use any libraries if we do, what kind of? 

p.s. I'm very sorry for my english, it is not my native language

**Comment by elementWebDev** [comment]
@anvarov  we haven't gotten anything together like that as far as I'm aware, however if you are working on something of the sort... as @chrisvneal posted above ...

> if you have a new feature that your working on that you aren't too sure you want to incorporate yet into the project (for example PHP/mySQL functionality, maybe another framework, etc.), create another branch for it on your local machine so you can also continue to work on the site with the regular stuff (Bootstrap classes, CSS, simple JavaScript) in your local [dev] branch.

> So your local branches would look something like this:

> **_typical branches we all work from_**
- > **[master]** - where you would pull the latest changes from the main repo
- > **[dev]** - where you make changes to be pushed back to your GitHub acct's [dev] branch to make the pull request to be reviewed

> **_separate branches - (languages everyone may not know yet)_**
- > **[php_idea]** - to be pushed (when your ready), reviewed and merged
- > **[ruby-idea]** - to be pushed (when your ready), reviewed and merged

**Comment by elementWebDev** [comment]
![products-info](https://user-images.githubusercontent.com/12195875/37371103-8aceb984-26cb-11e8-974b-2bc624db7af0.png)
idea proposal

**Comment by elementWebDev** [comment]
I have uploaded the project to my site <a href="https://elementwebdev.com/gwg/">https://elementwebdev.com/gwg</a> so we can see progress other than just code

**Comment by Cynth42** [comment]
@elementWebDev the idea proposal looks great!  Okay- cool and You can also see progress made on the site by clicking on the index page.

**Comment by chrisvneal** [comment]
@elementWebDev 
>On Sale items either on the home or on top of products page?

I can see how the Sale items on the main page would work, like we see on most e-commerce pages.

I like the idea of having the content switch as you select different categories, would we need anything like Ajax for that? I imagine PHP alone could, I'm actually interested in learning that. If you can make that happen by all means. 

If you have to remove any of the graphics I put there, please go ahead. I was thinking of a more professional look?

<hr>
@anvarov 

If you know some PHP or anything like that, go ahead and write some code in another branch like explained. I _am_ interested in merging other technologies with this project as we see fit.

**Think of this project as something to help "work the kinks out" and GitHub as well.**

>NOTE: Also, by the end of the week I'll be cleaning this place up a bit - sweep up the stagnant areas!

**Comment by Cynth42** [comment]
Alright, so when a buyer goes on the site and clicks on a headphone, it should take him to the item's description and ultimately to add item to cart.  How is the cart set up? Where can I find resources to write script for cart.js? Are you incorporating other languages like PHP and Ruby? What would be their purpose?

**Comment by elementWebDev** [comment]
@chrisvneal 

The hero images look awesome! We'll have to work on the css breakpoints for mobile.

**Some task ideas for those interested:**
manipulate the menu with jquery or vanilla .js 

make a products.js in JSON that includes: 
- product name
- description
- image
- price
- weight (optional- for shipping purposes)

I want to try and avoid php if we can, other than if we do logins etc. However since this is a front-end starter project we could just go with PayPal which takes care of logins etc  
<hr>

@Cynth42 
the cart isn't setup yet but you have the right idea for clicking on the image which shows the product larger and with a description as well as the add to cart button.

@GWGweb-projectgroup
I think getting the html down as a template to be filled in by javascript is a good idea.

**Comment by elementWebDev** [comment]
@Cynth42 
here's a sample link [client-side shopping cart](https://www.smashingmagazine.com/2014/02/create-client-side-shopping-cart/)

**Comment by chrisvneal** [comment]
@Cynth42 @elementWebDev 
 
As far as the cart is concerned, whatever functionality you want to incorporate is fine. I want to be careful and not step into creating an actual, real store with logins, etc. I'd expect to hit a login link and just have a modal pop up, but that's as far as that would go. No need to incorporate a database or anything... _with this project._

I haven't created too many JSON files, but I can learn. Is that necessary for this mockup? At this point, the focus is more on the front facing UI than anything _(using HTML, CSS, Bootstrap, and some helpful JS scripting)_. Let's see how far we get with that and the next phase would be to either continue building out an advanced mockup of the e-commerce site or start another project incorporating more intermediate technologies such as JSON, Ruby, PHP, etc.

All great ideas!

**Comment by elementWebDev** [comment]
I agree. thanks for clearing that up. I think we're doing pretty good so far.

**Comment by elementWebDev** [comment]
no we dont have to do json.. but definately a good idea for use on larger projects

**Comment by Cynth42** [comment]
I'm just waiting to see the HTML file for products, then the JS team can start working on products.js

**Comment by elementWebDev** [comment]
We need a couple hero images for sections:
- Computers 
- Tech & Gadgets
- Accessories
[Pexels](https://www.pexels.com/) is a pretty good resource for free images

**Comment by elementWebDev** [comment]
![products-screenshot](https://user-images.githubusercontent.com/12195875/37482310-50d240f8-2841-11e8-9989-91acb49e0810.png)

**Comment by elementWebDev** [comment]
![product-dropdown](https://user-images.githubusercontent.com/12195875/37490919-5b4d30fc-2859-11e8-88ae-d9b358e0e826.png)

This was more of what I had in mind

**Comment by elementWebDev** [comment]
oops the audio is supposed to be .hero-audio or similar naming not .hero-tech

**Comment by elementWebDev** [comment]
product transition
![transitions](https://user-images.githubusercontent.com/12195875/37491931-98e8cd1a-285c-11e8-9033-6f2a7d6333b0.png)

**Comment by Cynth42** [comment]
Hi guys!
Thank you all for the great progress!  I'll catch up over the weekend.  I'm working on my student story that has to be submitted tomorrow(Friday).

**Comment by chrisvneal** [comment]
@elementWebDev Good thinking, way ahead! I fixed a lot of those issues and I _did_ notice the link/menu arrangement. Also I'm just seeing these wireframe ideas for the first time.

* I did remove the **hero section** on those separate product sections though. If you had a better idea for that in the works, you can go ahead and add that back in there

* I removed the **headphones graphics** at the head of the products page. It continued to be an eye sore lol if we can get better images of families using electronics, stuff like that, it would look better. It would also cater more to our ideal "customer" I think

**Comment by chrisvneal** [comment]
@elementWebDev If you get a chance, can you create another issue going over ideas for the site's interactive functionality. Looks like you have some good ideas. I'll go over them!

**Comment by elementWebDev** [comment]
sounds good.. lots to keep me busy :) i uploaded the master to my server before i saw the comments, and was a little confused..lol bit it all makes sense now :)

**Comment by elementWebDev** [comment]
sorry about the late wireframes, these ideas came to me as I was working on the project, and thought it would be easy to work around for others and share the proposal

**Comment by ddpetty** [comment]
Does anyone have ideas for the computers page? I'm binge coding on Sunday
and I would like to stay consistent with other pages while adding a little
CSS flair.

**Comment by ddpetty** [comment]
I work just under full time so I have to fit a ton of time when I can.

**Comment by chrisvneal** [comment]
@ddpetty 

Nothing to worry about, do what you can. In the meantime, I can look over your **computers.html** page as we build a template for any other category pages, nice page btw! I sectioned the CSS off for it in _products.css_, so we can look at that separately. Before you start your code binge, remember to pull the latest changes from this repo's **[master]** branch.

@elementWebDev 

How do you like the design of the products page, is that something we can work with while including features from the wireframe above? I left the commented sections in **products.html** alone, what feature is that?

Also, I will help create content for the main page, **index.html**. If anyone has any ideas, let me know!

**Comment by chrisvneal** [comment]
@GWGweb-projectgroup

I added a [Project Page](https://github.com/GWGweb-projectgroup/practice-project/projects/2) for us whenever we get to the point where we're comfortable creating tasks in a project format. This project setup is built similar to the Trello app.

Also, **tomorrow** sometime when I get the chance, I'll be making some adjustments to the teams.

**Comment by elementWebDev** [comment]
I dont have much time this weekend, but I saw your ratings and will work on
this to make it respond to input. I found a good tutorial to work with.

On Mar 17, 2018 12:53 AM, "Chris Neal" <notifications@github.com> wrote:

@GWGweb-projectgroup <https://github.com/gwgweb-projectgroup>

I added a Project Page
<https://github.com/GWGweb-projectgroup/practice-project/projects/2> for us
whenever we get to the point where we're comfortable creating tasks in a
project format. This project setup is built similar to the Trello app.

Also, *tomorrow* sometime when I get the chance, I'll be making some
adjustments to the teams.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GWGweb-projectgroup/practice-project/issues/26#issuecomment-373902021>,
or mute the thread

**Comment by Cynth42** [comment]
Hey you all!
Submitted student story- hope you all submitted yours! I pulled the latest changes to my local.  See more html, css and js pages (onSale.html, audio.html, prroducts.css, styles.css, global_styles.css, product.js). Styling is mainly bootstrap?  Looking at product.js

**Comment by chrisvneal** [comment]
@GWGweb-projectgroup

Hey @Cynth42 

I submitted my story! I wasn't going to, but I had something to say at the last minute lol

As for **Bootstrap**, I figured since I wanted to learn it and @elementWebDev started out using the framework for the layout, it'd be good to work some of it into the project. I'm even considering using Bootstrap's [carousel](https://getbootstrap.com/docs/4.0/components/carousel/) for the main page! Are you familiar with [Bootstrap v4](https://getbootstrap.com/docs/4.0/getting-started/introduction/)?

**Comment by elementWebDev** [comment]
@GWGweb-projectgroup

looks like I gotta catch up from the weekend, good job!

Bootstrap Carousel tutorials
[BS docs](https://getbootstrap.com/docs/4.0/components/carousel/)
[w3schools tutorial](https://www.w3schools.com/bootstrap/bootstrap_carousel.asp)

**Comment by elementWebDev** [comment]
sorry @chrisvneal .. i just saw your link to the carousel docs

**Comment by elementWebDev** [comment]
@GWGweb-projectgroup

Just got a dynamic rating feature implemented on the product template (still in-progress).
I'm doing a PR next

![capture](https://user-images.githubusercontent.com/12195875/37623594-78f543fc-2b82-11e8-9653-0a2418b0e76c.PNG)

**Comment by Cynth42** [comment]
Glad you sent in your story@chrisvneal!  I'm familiar with bootstrap 4, and I'm looking over Carousel docs.

**Comment by Cynth42** [comment]
So the main page would be the  index.html?  Are we adding in some carousel slides? which elements are we targeting?

**Comment by MeganSpauldingCreative** [comment]
Hey guys! I'm hoping in here a little late to the game, and am pretty lost, even after reading up, honestly! Could be that it's late!

Would someone mind sharing what our current goals are? Thank you so much in advance!

**Comment by elementWebDev** [comment]
@Cynth42  
- index.html is the home page
- I'm not sure what you mean by targeted elements, just replace the images, unless you are adding thumbnails to the slider

@MeganSpauldingCreative 
- Pretty much we are building the pages, if you see something that could be improved go ahead and work on it locally and then create a pull request

**Comment by chrisvneal** [comment]
@MeganSpauldingCreative you were removed as a member along with other inactive members. If you want to be a member, you have to sign up for something and contribute code in that area. 

One of the other members reached out saying they didn't get emails, I don't know if that's the case with you, if it is my apologies, but that would be an issue on your end. You were part of a group that when I looked to see who was actually contributing besides sign up, they were inactive and to avoid people just sitting as members, you were all removed.

**Comment by elementWebDev** [comment]
lol...  that last 2 messages got sent in tandem

**Comment by chrisvneal** [comment]
@elementWebDev 

Anybody else I removed can sign up to just be a contributor. I know people have different schedules and everything but there were a lot of members not doing contributing to the code base.

**Comment by elementWebDev** [comment]
@chrisvneal  I understand, I had been trying to figure out what to say and was going to mention contacting you about the team

**Comment by elementWebDev** [comment]
that was good timing

**Comment by chrisvneal** [comment]
@elementWebDev 

Yeah I tried to let everyone know, some people may have not been getting the notifications. I would have at least liked for some to come back and check on the progress of the group they signed up for as I did make notice of cleaning up the group of people who seemed to be inactive.

The project is actually coming along nice and I'll take a look at the pull requests when I come back to it shortly.

**Comment by elementWebDev** [comment]
@chrisvneal 

sounds good

**Comment by Cynth42** [comment]
**_index.html is the home page
I'm not sure what you mean by targeted elements, just replace the images, unless you are adding thumbnails to the slider_**

What is supposed to be done with the home page?  What images should be sliding onto the homepage?   I'm looking at the wireframe to give me leads. Please make this thing clear so we can start working on it.  I'm fired up and ready to do it! lol

**Comment by elementWebDev** [comment]
@Cynth42 
I would use the carousel to show featured products and possibly a special holiday discount image, basically it's our showcase.

@GWGweb-projectgroup

Just an update...
![details-button](https://user-images.githubusercontent.com/12195875/37681459-fc305f06-2c43-11e8-9e35-212c8906196f.png)
![details](https://user-images.githubusercontent.com/12195875/37681471-025256be-2c44-11e8-9a8d-ee746f5eadc1.png)

**Comment by chrisvneal** [comment]
Looking good @elementWebDev 

I implemented the carousel on index.html. Make changes as you see fit, I like some of the images

A few questions 

* Is your **product.html** file a template for a _roll over/modal_? That looks pretty nice, we can use it

* How will **ratings.js** and **ratings.html** be implemented?

**Comment by elementWebDev** [comment]
@chrisvneal 

this is actually a dropdown from the details, but a modal would be better... sorry, a little rusty with BS

**Comment by chrisvneal** [comment]
I'm going to close this issue, unless any of you need to open it again. 

* I prefer that another issue be opened pertaining to the topic in question and the discussion will be based on that 

* General discussion Issues can always be open if you like. If it's associated with a **pull request**, create a comment in the pull request!

This closes Issue #26
