### ISSUE TITLE
Froala Design Blocks - inspiration for components

### ISSUE THREAD

**Issue by chrisvneal** [GWGweb-projectgroup/practice-project#36]
@GWGweb-projectgroup/layout 
@GWGweb-projectgroup/index-html 

I came across the **[froala/design blocks](https://github.com/froala/design-blocks)** GitHub account that has some good templates for website components. Check them out when you get a chance for inspiration!

I'll be going there again to see if I can get some ideas!

**Comment by elementWebDev** [comment]
I could've used this awhile ago...lol

**Comment by Cynth42** [comment]
Just pulled latest changes from GWG eCommerce.  I see great progress, but I'm not sure or don't know what to do.  Need direction.

**Comment by elementWebDev** [comment]
@Cynth42
So far..

 We need a script for the nav to change (current) to active page,

The cart.js needs work as well as html to be integrated

If anyone has other feedback / ideas please post them

**Comment by Cynth42** [comment]
Okay @elementWebDev - cart.js needs script to add shopping cart at checkout?  Looking for ideas.  What's up with the HTML team?

**Comment by chrisvneal** [comment]
@elementWebDev @Cynth42 

I see us adding any interactivity a little later on after we build things out a little more because that could have some effect on what we decide to script, but if you have ideas go on ahead, let's see.

@Cynth42 the main **index.html** page could use some attention. At the moment, I like the structure of the three columns. We could still use **.rows** and **.cols** within those columns as well for more content. So let's stick with that for the time being, unless you have more efficient ideas.

Thank you both for participating!
