### ISSUE TITLE
Merge Conflicts

### ISSUE THREAD

**Issue by chrisvneal** [GWGweb-projectgroup/practice-project#48]
@elementWebDev I merged your recent commits to the **[dev branch]** first and then @ddpetty's commits to the same branch. Here's what happened _(and I'm glad that it did so I can show you all if you haven't seen too many merge conflicts)_:

@ddpetty created a new **computers.html** file which is fine, but a conflict happened because her _**computers.html**_ link conflicted with @elementWebDev's _**products.html#computers**_ link.

<br>

![ddpetty_merge](https://user-images.githubusercontent.com/12589660/37449931-2d546cb2-27d0-11e8-997a-d9e4e18d70ac.jpg)

**Easy fix:** We can just make @elementWebDev's _"View More"_ link in the computers section link to _computers.html_. Totally fine as long as additional pages are styled similar to the main pages we have established.

We shouldn't have too many merge conflicts as long as we stick to assigned areas, but that doesn't mean you can't break out and help out other teams with your ideas! Merge conflicts merely just force you to make a decision on which code you want to keep. Luckily, that was an easy fix because you guys and gals are awesome!!! 👍

**Comment by elementWebDev** [comment]
That was my first merge conflict.. I had noticed it when I was trying to preview the index.html menu. lol It wasn't showing up right, and I kept getting an error then fixing it... at least I will know for future reference, and can check. I thought it was one of the first versions of the menu.

**Comment by ddpetty** [comment]
Thank you for letting me know! This is my first time contributing to a
group project so I'm sorry for the conflicts. I'll be learning from these.

**Comment by elementWebDev** [comment]
No need to be sorry.. we're all learning here :)

**Comment by elementWebDev** [comment]
That was my first reply by email.. Forgot to delete quoted message

**Comment by chrisvneal** [comment]
Yeah @ddpetty no more conflicts! lol Nah merge conflicts are part of the game. When you made your changes, others were making changes too. 

We all don't know who's doing what, that's actually the fun part and they can all be rectified easily. Thanks for the commits!

**Comment by elementWebDev** [comment]
Absolutely awesome working with a team... This is my first. I have worked alone for years and taking about a month per project. The power in the team is fresh ideas, breaking things down to smaller digestable chunks, and help... Lol
