### ISSUE TITLE
Re-Sign Up & Confusing button placement

### ISSUE THREAD

**Issue by MeganSpauldingCreative** [GWGweb-projectgroup/practice-project#74]
Sorry if me making a new issue is messing up the workflow, delete if not allowed, I just wasn't sure how to respond since a new issue hadn't been opened yet ***Sorry GitHub Newbie...***

My family has been out of town, so I am late to the game! But jumping right in! I'm a web designer by trade, so hopefully I can be of some help! 

Secondly, I was going through the site, and thought the "view more" button was extremely confusing under the reviews. Sorry if this has already been disgusted. When I clicked on it I was expecting to see more reviews. What do you think about refactoring layout to make it more user friendly? Would putting the reviews under each item be better? And then maybe just having a cumulative review section at the bottom or top of the page that gives some of the best reviews and notes what item it is for? 

Additionally I noticed tablets were under accessories. Would we want to rename that section to tablets? I ask because when someone says "accessories" they are normally referring to cases or chargers, etc.

What do you guys think?

I made some edits to the header images on the product pages for starters!

**Comment by elementWebDev** [comment]
You're on the right track, I was thinking the same about the reviews being
towards the bottom and / or on the single product pages.

The categories have placeholder info until we have something more relevant.

**Comment by chrisvneal** [comment]
I would assume that the button would take me to a separate page more items, not really produce a dropdown of more items. What would be better though, a more minimal button and some way to indicate that users will be taken to a different page?

**Comment by MeganSpauldingCreative** [comment]
@chrisvneal That's a good thought. I will work on this tonight to get something that maybe is more user friendly, and push to a temporary branch for approval!

**Comment by MeganSpauldingCreative** [comment]
I took probably way to long trying to sort this out when the most obvious answer was right in front of my eyes! I moved the button to above the reviews instead of after, and also added a containing border on each of the sections to help break the page up. If you guys like what I did, we can go ahead and close this issue!

**Comment by chrisvneal** [comment]
Hey @MeganSpauldingCreative  I'll take a look at things. It looks like your pull request won't let me merge until some issues are fixed. 

Sounds like a great idea, I was thinking that users would be compelled to **View More** after reading **Reviews** but I guess it doesn't matter at this point. I'll see if I can fix what's causing an issue. 

Good job! 👍
