### ISSUE TITLE
Adding Carousel in onsale.html

### ISSUE THREAD

**Issue by Cynth42** [GWGweb-projectgroup/practice-project#77]
Hi Guys!
looking at onSale.html and would like to add carousel to some images in labels folder (discount images). Want to add them at the top of the page.  Any suggestions?

**Comment by elementWebDev** [comment]
@Cynth42 

off the top of my head... having a div with 2 images
- product img
- label image on top as long as its background is transparent

**Comment by chrisvneal** [comment]
@Cynth42 @elementWebDev 
Best thing would be to copy the code from index.html and adjust from there. I have to fix the sizing on the headers though due to recent commits.

**Comment by Cynth42** [comment]
Alright, I wanted to add it right above audio headphone:

<img width="1273" alt="screen shot 2018-03-20 at 11 38 57 pm" src="https://user-images.githubusercontent.com/14208716/37693722-06eecbb8-2c98-11e8-824a-67dd20b76012.png">

**Comment by chrisvneal** [comment]
@Cynth42 Yeah, that's where it's supposed to go. It can be the main page header for now.

**Comment by Cynth42** [comment]
Alright, was wondering how many images? up to three: big sale, discount1, discount2- did you say to add transparent background @elementWebDev ?

**Comment by chrisvneal** [comment]
@Cynth42 

It's all up to you, however many you feel like contributing. Key points to the project:

* have fun, practice what you need to learn and contribute those skills somehow to the project
* be consistent with the main idea and overall style/layout of the site

Basically, you have free roam to add however many pictures you want, as long as the content is within scope  of the main project _(i.e. tech products, electronics and so on)_

As for the transparent background for the header, take a look at what I've done already or give this a quick read:

- **CSS-tricks** snippet/tutorial on [adding transparent backgrounds in CSS](https://css-tricks.com/snippets/css/transparent-background-images/)

I may apply this technique myself and recode the overlay properly.

**Comment by chrisvneal** [comment]
@GWGweb-projectgroup 

Don't mean to be a nag, but this is a quick reminder to pull from the **[master]** branch for the latest changes before laying your changes on top of anything and trying to get them merged in. We will get less merge conflicts this way. 😄

**Comment by Cynth42** [comment]
So this the changes I made to onsale.html. Added carousel slides that comprised of 4 images.  Uploaded is the first image. Please let me know if I need to make any adjustments before pushing for merging:
<img width="1206" alt="screen shot 2018-03-21 at 7 09 33 pm" src="https://user-images.githubusercontent.com/14208716/37742404-d568cde2-2d3b-11e8-925b-85a856761ba1.png">

**Comment by elementWebDev** [comment]
@Cynth42 

I meant it depends on whether the image itself has a transparent background. 

This is looking good :)

**Comment by Cynth42** [comment]
Right @elementWebDev, I think all the images have transparent background.  They look good against the banner container:
<img width="1263" alt="screen shot 2018-03-21 at 8 07 14 pm" src="https://user-images.githubusercontent.com/14208716/37744106-dc31417e-2d43-11e8-8ee3-02fab90d3fca.png">

**Comment by elementWebDev** [comment]
@Cynth42  they do, I was just looking at them, the other images need to be optimized, which I'll probably take care of

**Comment by Cynth42** [comment]
Great idea @elementWebDev and you'll also need to adjust the page so that the footer is in placed.  I noticed that after adding the slides, there was no space for the footer even after I reduced the "view more" buttons.  Please take a look at that.  Thanks :)

**Comment by elementWebDev** [comment]
I can't view your work until it's merged, but it's probably an extra or missing div

**Comment by Cynth42** [comment]
Alright, I'll check to see if there's a missing div or an extra one before pushing.

**Comment by elementWebDev** [comment]
you can post your code here too

**Comment by elementWebDev** [comment]
background: cover;

is good for use on large banner images that look squished as it will basicly crop what is viewable and you can add images on top

**Comment by elementWebDev** [comment]
@Cynth42 
you can try that later.. Dont worry about it now.
