### ISSUE TITLE
Create Modal branch

### ISSUE THREAD

**Issue by chrisvneal** [GWGweb-projectgroup/practice-project#84]
@GWGweb-projectgroup 

The **[create_modal]** branch is just a quick _test/feature_ branch for anyone invloved to test development of a modal system for "product details pop ups".

Please ask if you have any trouble working with this branch.

**Comment by elementWebDev** [comment]
Not sure if we should go with a modal for product details after messing with ideas (because of the amount of info).
However, modals can definitely be used for individual items, such as larger product pictures, a small list of reviews, different product variations, etc.

Here's a better layout mockup for the single product page.
...thoughts?

![single-product](https://user-images.githubusercontent.com/12195875/37739547-ad4364cc-2d17-11e8-8b06-1ad82ffd2770.png)

**Comment by elementWebDev** [comment]
Sorry for things not looking the greatest, I cancelled my Adobe Print/Web subscription after 20 years! LOL

I started using open source software when I got into Udacity. :)

**Comment by chrisvneal** [comment]
@elementWebDev 

lol looks great to me, let's do it. I really didn't want to create that branch anyway and the code seemed like too much for what we're trying to do. I'll delete it.

Also, 

* _PHP_ would seem perfect for something like this. I've forgotten a lot of it but it seems you may be more familiar. Just a thought I had. 

* I'm stuck on the whole _PHP vs Node.js_ thing now and just learning more advanced JavaScript until I figure out which way I want to go. Any thoughts on what I should look into first?

Great mockup btw

**Comment by elementWebDev** [comment]
@chrisvneal 

I will work on putting something together in .js or php to fill in the product info.. I worked with php in CMS platforms like WordPress, ZenCart, OpenCart, etc. which already have the base back-end for you. I'm familiar with it but by no means an expert. 

@GWGweb-projectgroup
I may need someone to work on building out the html for the wireframe above while I do this. It doesn't need to be perfect, I just need placeholders so I can replace the info.

Thanks all! We're doing a great job!

**Comment by chrisvneal** [comment]
@GWGweb-projectgroup 

It's not connected to anything yet, but check out **[product.html](https://gwgweb-projectgroup.github.io/practice-project/product.html)**

@elementWebDev This may serve as a template, let me know if anything needs adjusting.

**Comment by elementWebDev** [comment]
@chrisvneal 

looks great, thanks for jumping on that so quick lol
