### ISSUE TITLE
We have approval for pics and descriptions!

### ISSUE THREAD

**Issue by elementWebDev** [GWGweb-projectgroup/practice-project#90]
I just got approval to use product info and images... I will be gathering :)
Suggestions are welcome

**Comment by elementWebDev** [comment]
@GWGweb-projectgroup

Backup plan...
In the case that only 10% will move on to next round...

I am interested in freelancing or getting a team together. If anyone is interested please let me know. I have experience with wholesalers, distributors and resellers. Theres alot of talent here just waiting to be unleashed

**Comment by chrisvneal** [comment]
What's this about? You starting a business or something? For this project? lol

**Comment by elementWebDev** [comment]
Ive been working with stores since 2009, with a variety of platforms.. Im just thinking ahead, those interested would of course need to continue learning. There are alot of free resources. Im used to doing everything myself.

**Comment by chrisvneal** [comment]
Good to know! I'll keep this info in my back pocket 😉

**Comment by Cynth42** [comment]
@elementWebDev - This sounds interesting~ great back plan! :)
